<a href="https://colab.research.google.com/github/odimusv/ISYS2001-A2-Budget-Buddy/blob/main/starter_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏦 Project Overview

Welcome to your **Smart Finance Assistant** development journey! This notebook will evolve from basic CSV processing to a complete AI-powered finance application.

**Final Application Components:**
- 💬 **AI Chat Interface** - Financial advice personality
- 📊 **Data Analysis** - CSV transaction processing  
- 🔍 **RAG System** - Retrieval from financial documents
- 🛠️ **Custom Tools** - Calculators and utilities
- 🌐 **Gradio UI** - Professional web interface

**Development Approach**: Build progressively from foundation to advanced features, using AI collaboration throughout.

---

# 🚀 Getting Started: Foundation Setup

## Initial Setup
This cell installs the necessary libraries. In a Colab environment, you would uncomment the first line.

In [ ]:
# Uncomment the line below when running in Google Colab
!pip install gradio pandas hands-on-ai

# Import core libraries
import pandas as pd
import numpy as np
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

print("📦 Core libraries loaded successfully!")
print(f"Pandas version: {pd.__version__}")

## Hands-on-AI Configuration

Set up the hands-on-ai package for advanced features (chat, RAG, tools):

In [ ]:
import os
from getpass import getpass

# Configure hands-on-ai server connection
os.environ['HANDS_ON_AI_SERVER'] = ' https://ollama.locollm.org'
os.environ['HANDS_ON_AI_MODEL'] = 'gemma3:4b'
os.environ['HANDS_ON_AI_API_KEY'] = 'Curtin2026ISYS20015002'

print("🔑 Hands-on-AI configured successfully!")

The API key this semester is:  **isys2001-assignment-key**

## Connection Test

Test that everything is working correctly:

In [ ]:
from hands_on_ai.chat import get_response

# Test the connection to the hands-on-ai server
try:
    response = get_response("Hello! I'm building a Smart Finance Assistant.")
    print("✅ Hands-on-AI connection successful!")
    print(f"Response: {response}")
except Exception as e:
    print(f"❌ Connection issue: {e}")
    print("You can still work on the data processing foundation without this.")

---

# 🏗️ Foundation: Data Processing Skills

Before building advanced features, establish solid data processing foundations. This section focuses on CSV transaction analysis - the core of your finance assistant.

## Foundation Skill Checkpoint ✅

**Master these basics before advancing to chat/RAG/tools:**
- [ ] Load and clean CSV transaction data
- [ ] Handle real-world data issues (dollar signs, missing values)
- [ ] Calculate spending summaries by category  
- [ ] Generate business-appropriate insights
- [ ] Format output for professional presentation
- [ ] Test functions with various data scenarios

::: {.callout-tip}
## 🤖 AI Collaboration Strategy

For this foundation work, use AI to:
1. **Generate initial code** with specific business context
2. **Handle data cleaning** and validation
3. **Create professional formatting** for outputs
4. **Suggest business insights** from data patterns
5. **Help with testing** edge cases and error handling

**Remember**: You're directing AI like a junior developer - always review and improve their suggestions!
:::

## Sample Transaction Data Setup

Create or load sample transaction data to work with:

In [ ]:
# 🤖 AI Collaboration Opportunity:
# Ask AI to help you create realistic sample transaction data
# Include Australian businesses and various spending categories

# Sample data structure for testing
sample_transactions = {
    'Date': ['2024-08-01', '2024-08-02', '2024-08-03', '2024-08-04', '2024-08-05'],
    'Amount': ['$45.50', '$12.00', '$89.95', '$3.50', '-$25.00'],  # Note: includes $ signs and refund
    'Category': ['Groceries', 'Transport', 'Entertainment', 'Coffee', 'Refund'],
    'Description': ['Woolworths', 'Opal Card', 'Concert Tickets', 'Campus Cafe', 'Returned Item']
}

# Create DataFrame from sample data
df_sample = pd.DataFrame(sample_transactions)
print("📋 Sample transaction data created:")
print(df_sample)

---

# 📊 Six-Step Development Methodology

Your notebook must demonstrate the six-step methodology with clear evidence of AI collaboration at each step.

## STEP 1: Understand the Problem

**🎯 Define Your Finance Problem**

In this section, clearly state your chosen finance problem in business terms.

::: {.callout-note}
## Problem Definition Template

*Example: "I want to help people understand their spending habits by analyzing their bank transaction exports. The system should identify spending patterns, highlight potential savings opportunities, and provide actionable financial insights in easy-to-understand language."*

**🤖 AI Prompt to Try:**
```
"Help me brainstorm specific personal finance problems that could be solved
with a CSV analysis tool. I'm interested in helping people with budgeting
and spending awareness. What are common financial challenges that data
analysis could address?"
```

**Your Problem Statement:**
Many students and young adults struggle to understand where their money goes. A Budget Buddy will help users upload their transaction data, summarise their spending and receive practical and useful budgeting advice.

## STEP 2: Identify Inputs and Outputs

**📥 Define Your Data Flow**

Clearly specify what data you'll work with and what insights you'll generate.

## Input/Output Analysis Template

**Inputs:**
- CSV file with transaction data (columns: Date, Amount, Category, Description)
- User preferences (spending goals, categories to focus on)
- Time period for analysis

**Outputs:**
- Total spending summary by category
- Average spending patterns
- Spending trend analysis
- Actionable savings recommendations
- Visual spending breakdown (future enhancement)

**🤖 AI Prompt to Try:**
```
"For a personal finance assistant that analyzes CSV transaction data,
what are the most valuable inputs I should collect and outputs I should
provide? Consider both technical data processing and business value
for the user."
```

**Your Input/Output Definition:**

Inputs:

* Transaction CSV
* Date, amount, category and description for expense inputs for analysis


Outputs:

* Transaction table showing data quality and clean amounts
* Category summary that shows total avg, count and percentage by category
* Spending report summarises total spending and budget status
* Budget Buddy response gives advice based on the uploaded data

## STEP 3: Work the Problem by Hand

**✋ Manual Calculation Examples**

Show 2-3 worked examples to understand the logic before coding.


## Example Business Calculation

Given this sample data:

| Date | Amount | Category | Description |
|------|--------|----------|-------------|
| 2024-08-01 | $45.50 | Groceries | Woolworths |
| 2024-08-02 | $12.00 | Transport | Opal Card |
| 2024-08-03 | $89.95 | Entertainment | Concert |
| 2024-08-04 | -$15.00 | Refund | Returned item |

**Manual Calculations:**
- Total Spending: $45.50 + $12.00 + $89.95 - $15.00 = $132.45
- By Category: Groceries $45.50, Transport $12.00, Entertainment $89.95
- Average Transaction: $132.45 ÷ 4 = $33.11
- Insight: Entertainment represents 67% of positive spending

**🤖 AI Prompt to Try:**
```
"Give me 3 realistic examples of Australian transaction data with different
scenarios (normal spending, refunds, large purchases). Show me how to manually
calculate meaningful financial insights from each scenario."
```

**Your Manual Examples:**

Manual calculation 1 – Positive spending total
Only positive amounts count as spending.

[ 45.50 + 12.00 + 89.95 + 3.50 = 150.95 ]

Positive spending total = $150.95

Manual calculation 2 – Net spending after refund
The refund/credit reduces the net total, but Budget Buddy should still track it separately.

[ 150.95 - 25.00 = 125.95 ]

Net spending = $125.95
Refunds/credits = $25.00
## STEP 4: Write Pseudocode

**📝 Plan Your Solution Logic**

Sketch the algorithm in plain English before coding.


## Pseudocode Template

```
FUNCTION analyze_spending_data(csv_file):
    // Step 1: Load and validate data
    - Read CSV file into DataFrame
    - Check for required columns (Date, Amount, Category, Description)
    - Handle missing or invalid data
    
    // Step 2: Clean financial data  
    - Remove dollar signs from Amount column
    - Convert to numeric values
    - Separate positive spending from refunds
    
    // Step 3: Calculate business metrics
    - Group transactions by category
    - Calculate totals, averages, counts per category
    - Identify spending patterns and outliers
    
    // Step 4: Generate insights
    - Calculate percentages of total spending
    - Identify top spending categories
    - Suggest potential savings opportunities
    
    // Step 5: Format for presentation
    - Create business-friendly output
    - Include currency formatting
    - Add explanatory text for insights
    
    RETURN formatted_analysis
```

**🤖 AI Prompt to Try:**
```
"Review my pseudocode for analyzing spending data from a CSV. Are there any
edge cases I'm missing? What business logic should I add to make this more
valuable for personal finance insights?"
```


**Your Pseudocode:**

FUNCTION BudgetBuddy(csv_file, monthly_budget, user_question):

    LOAD csv_file into a table

    CHECK the table has Date, Amount, Category, Description
    IF required columns are missing:
        RETURN a helpful error message

    CLEAN the data:
        convert Date into real dates
        remove "$", commas and spaces from Amount
        convert Amount into numbers
        drop rows where Date or Amount cannot be cleaned
        label each row as Spending, Refund/Credit, or Zero/No spend

    ANALYSE spending:
        keep positive Amount values for spending totals
        keep negative Amount values for refunds
        calculate total positive spending
        calculate total refunds
        calculate net spending
        group positive spending by Category
        calculate total, average, count and percentage for each Category
        identify the biggest spending Category
        compare total spending to monthly_budget if one is entered

    GENERATE advice:
        explain the top spending category
        warn if the user is over budget
        suggest one practical saving action
        mention refunds separately so they do not hide real habits

    CHAT/RAG:
        use the spending summary as context for Budget Buddy chat
        retrieve relevant budgeting guide notes for finance questions
        combine retrieved notes with the user's transaction summary

    TOOL:
        calculate months needed for a savings goal

    DISPLAY:
        show report, category table, cleaned table, chat, RAG answer and tool output in Gradio

## STEP 5: Convert to Python

**💻 Implementation with AI Collaboration**

Now implement your solution using AI assistance. Focus on creating professional, business-appropriate code.


## 🤖 Implementation Strategy

**Effective AI Prompts for Implementation:**
```
"I'm implementing a Smart Finance Assistant. Based on my pseudocode, please create
a Python function that [specific functionality]. The code should:
- Handle real-world CSV data issues (dollar signs, missing values)
- Include clear comments explaining business logic
- Use professional variable names
- Format output for business presentation
- Include basic error handling"
```

**Remember to critique and improve AI responses before using them!**
:::

### Foundation Data Processing Functions

In [57]:
# 🤖 AI Collaboration: Data Loading and Cleaning Function
# Ask AI to help you create a robust data loading function

def load_and_clean_transaction_data(file_path):
    """
    Load and clean transaction data for the Smart Finance Assistant

    🤖 AI Collaboration Prompt:
    "Create a function to load CSV transaction data with Date, Amount, Category,
    Description columns. Handle dollar signs in Amount, missing values, and
    data validation. Include clear business-focused error messages."

    Args:
        file_path: Path to CSV file, file object, or pandas DataFrame
    Returns:
        pandas.DataFrame: Cleaned transaction data
    """
    import os
    import pandas as pd
    import numpy as np
    from pandas.errors import EmptyDataError

    if file_path is None:
        raise ValueError("Please provide a transaction CSV file or a pandas DataFrame.")

    try:
        if isinstance(file_path, pd.DataFrame):
            df = file_path.copy()
        else:
            csv_source = (
                file_path.name
                if hasattr(file_path, "name") and not isinstance(file_path, (str, bytes, os.PathLike))
                else file_path
            )
            df = pd.read_csv(csv_source)
    except EmptyDataError:
        raise ValueError(
            "The transaction file is empty. Please upload a CSV with Date, Amount, Category and Description columns."
        )
    except FileNotFoundError:
        raise ValueError(
            "The transaction file could not be found. Please check the file path or upload the CSV again."
        )
    except Exception as e:
        raise ValueError(
            f"Unable to load the transaction CSV. Please check the file format. Details: {e}"
        )

    if df.empty:
        raise ValueError("The transaction file has no rows to analyse.")

    df.columns = [str(col).strip() for col in df.columns]

    required_columns = ["Date", "Amount", "Category", "Description"]
    column_lookup = {str(col).strip().lower(): col for col in df.columns}
    missing_columns = [col for col in required_columns if col.lower() not in column_lookup]

    if missing_columns:
        raise ValueError(
            "Missing required transaction column(s): "
            + ", ".join(missing_columns)
            + ". The CSV must include Date, Amount, Category and Description."
        )

    df = df[[column_lookup[col.lower()] for col in required_columns]].copy()
    df.columns = required_columns
    df = df.dropna(how="all")

    if df.empty:
        raise ValueError("The transaction file only contains blank rows.")

    df["Category"] = df["Category"].fillna("Uncategorised").astype(str).str.strip()
    df.loc[df["Category"].isin(["", "nan", "None", "NaN"]), "Category"] = "Uncategorised"

    df["Description"] = df["Description"].fillna("No description provided").astype(str).str.strip()
    df.loc[df["Description"].isin(["", "nan", "None", "NaN"]), "Description"] = "No description provided"

    cleaned_amount = (
        df["Amount"]
        .astype(str)
        .str.strip()
        .str.replace("−", "-", regex=False)
        .str.replace(r"[\$,]", "", regex=True)
        .str.replace(r"^\((.*)\)$", r"-\1", regex=True)
    )
    cleaned_amount = cleaned_amount.replace(["", "nan", "NaN", "None", "none"], pd.NA)

    df["Amount"] = pd.to_numeric(cleaned_amount, errors="coerce")

    invalid_amounts = df["Amount"].isna()
    if invalid_amounts.any():
        bad_rows = (df.index[invalid_amounts] + 2).astype(str).tolist()
        raise ValueError(
            "Some transaction amounts could not be read as numbers. "
            f"Please check CSV row(s): {', '.join(bad_rows[:5])}."
        )

    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

    invalid_dates = df["Date"].isna()
    if invalid_dates.any():
        bad_rows = (df.index[invalid_dates] + 2).astype(str).tolist()
        raise ValueError(
            "Some transaction dates could not be read. "
            f"Please check CSV row(s): {', '.join(bad_rows[:5])} and use a format like YYYY-MM-DD."
        )

    df = df.sort_values("Date").reset_index(drop=True)

    df["Transaction_Type"] = np.select(
        [df["Amount"] > 0, df["Amount"] < 0],
        ["Expense", "Refund"],
        default="Zero"
    )

    df["Month"] = df["Date"].dt.to_period("M").astype(str)

    return df

# Test your function
clean_data = load_and_clean_transaction_data(df_sample)
print(clean_data)

        Date  Amount       Category      Description Transaction_Type    Month
0 2024-08-01   45.50      Groceries       Woolworths          Expense  2024-08
1 2024-08-02   12.00      Transport        Opal Card          Expense  2024-08
2 2024-08-03   89.95  Entertainment  Concert Tickets          Expense  2024-08
3 2024-08-04    3.50         Coffee      Campus Cafe          Expense  2024-08
4 2024-08-05  -25.00         Refund    Returned Item           Refund  2024-08

In [58]:
# 🤖 AI Collaboration: Spending Analysis Function
# Ask AI to help you create comprehensive spending analysis

def analyze_spending_patterns(df):
    """
    Analyze spending patterns and generate business insights

    🤖 AI Collaboration Prompt:
    "Create a function that analyzes spending by category, calculates percentages,
    identifies top spending areas, and generates actionable financial insights
    formatted for business presentation."

    Args:
        df: Cleaned transaction DataFrame
    Returns:
        dict: Analysis results and insights
    """
    import pandas as pd

    if not isinstance(df, pd.DataFrame):
        raise ValueError(
            "Spending analysis needs a pandas DataFrame created by load_and_clean_transaction_data()."
        )

    required_columns = {"Date", "Amount", "Category", "Description"}
    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        raise ValueError(
            f"Cannot analyse spending because these columns are missing: {', '.join(sorted(missing_columns))}."
        )

    if df.empty:
        raise ValueError("There are no transactions to analyse.")

    working_df = df.copy()
    working_df["Amount"] = pd.to_numeric(working_df["Amount"], errors="coerce")

    if working_df["Amount"].isna().any():
        raise ValueError("The Amount column contains invalid values. Please clean the data before analysis.")

    working_df["Date"] = pd.to_datetime(working_df["Date"], errors="coerce")

    if working_df["Date"].isna().any():
        raise ValueError("The Date column contains invalid values. Please clean the data before analysis.")

    expenses = working_df[working_df["Amount"] > 0].copy()
    refunds = working_df[working_df["Amount"] < 0].copy()

    total_spending = float(expenses["Amount"].sum())
    total_refunds = float(abs(refunds["Amount"].sum()))
    net_spending = float(working_df["Amount"].sum())

    if total_spending > 0:
        category_summary = (
            expenses.groupby("Category", as_index=False)
            .agg(
                TotalSpent=("Amount", "sum"),
                TransactionCount=("Amount", "count"),
                AverageTransaction=("Amount", "mean")
            )
            .sort_values("TotalSpent", ascending=False)
            .reset_index(drop=True)
        )

        category_summary["Percentage"] = (category_summary["TotalSpent"] / total_spending * 100).round(2)
        category_summary["TotalSpent"] = category_summary["TotalSpent"].round(2)
        category_summary["AverageTransaction"] = category_summary["AverageTransaction"].round(2)
        category_summary["FormattedTotal"] = category_summary["TotalSpent"].map(lambda value: f"${value:,.2f}")

        top_row = category_summary.iloc[0]
        top_category = str(top_row["Category"])
        top_category_amount = float(top_row["TotalSpent"])
        top_category_percentage = float(top_row["Percentage"])

        largest_row = expenses.sort_values("Amount", ascending=False).iloc[0]
        largest_transaction = {
            "Date": largest_row["Date"].strftime("%Y-%m-%d"),
            "Amount": float(largest_row["Amount"]),
            "Category": str(largest_row["Category"]),
            "Description": str(largest_row["Description"])
        }
    else:
        category_summary = pd.DataFrame(
            columns=[
                "Category",
                "TotalSpent",
                "TransactionCount",
                "AverageTransaction",
                "Percentage",
                "FormattedTotal"
            ]
        )
        top_category = None
        top_category_amount = 0.0
        top_category_percentage = 0.0
        largest_transaction = None

    discretionary_categories = [
        "Coffee",
        "Dining",
        "Entertainment",
        "Shopping",
        "Takeaway",
        "Restaurants",
        "Subscriptions"
    ]

    discretionary_spending = float(
        expenses[expenses["Category"].isin(discretionary_categories)]["Amount"].sum()
    )

    discretionary_percentage = (
        discretionary_spending / total_spending * 100
        if total_spending > 0
        else 0.0
    )

    refund_summary = (
        refunds.assign(RefundAmount=refunds["Amount"].abs())
        .groupby("Category", as_index=False)
        .agg(
            TotalRefunds=("RefundAmount", "sum"),
            RefundCount=("RefundAmount", "count")
        )
        .sort_values("TotalRefunds", ascending=False)
        .reset_index(drop=True)
        if not refunds.empty
        else pd.DataFrame(columns=["Category", "TotalRefunds", "RefundCount"])
    )

    date_start = working_df["Date"].min()
    date_end = working_df["Date"].max()
    days_covered = max((date_end - date_start).days + 1, 1)

    business_insights = []

    if total_spending == 0:
        business_insights.append(
            "No positive spending transactions were found; the data appears to contain only refunds or zero-value transactions."
        )
    else:
        business_insights.append(
            f"Your largest spending category is {top_category}, accounting for "
            f"${top_category_amount:,.2f} ({top_category_percentage:.1f}% of spending)."
        )

        if top_category_percentage >= 35:
            business_insights.append(
                f"{top_category} is a major budget driver. A 10% reduction in this category "
                f"could save about ${top_category_amount * 0.10:,.2f} over this period."
            )

        if discretionary_percentage >= 40:
            business_insights.append(
                f"Flexible lifestyle categories such as coffee, dining and entertainment make up "
                f"{discretionary_percentage:.1f}% of spending, so small habit changes could have a noticeable impact."
            )

        coffee_total = (
            float(category_summary.loc[category_summary["Category"].eq("Coffee"), "TotalSpent"].sum())
            if not category_summary.empty
            else 0.0
        )

        if coffee_total > 0:
            business_insights.append(
                f"Coffee spending totals ${coffee_total:,.2f}. "
                "Setting a weekly coffee cap is a simple student-friendly savings action."
            )

        daily_average = total_spending / days_covered
        business_insights.append(
            f"Average daily spending across the period is ${daily_average:,.2f}, "
            f"based on {days_covered} day(s) of transactions."
        )

    if total_refunds > 0:
        business_insights.append(
            f"Refunds total ${total_refunds:,.2f}. "
            "They are tracked separately so they do not hide your real spending habits."
        )

    return {
        "total_spending": round(total_spending, 2),
        "total_refunds": round(total_refunds, 2),
        "net_spending": round(net_spending, 2),
        "transaction_count": int(len(working_df)),
        "expense_transaction_count": int(len(expenses)),
        "refund_transaction_count": int(len(refunds)),
        "average_expense": round(float(expenses["Amount"].mean()), 2) if not expenses.empty else 0.0,
        "category_count": int(expenses["Category"].nunique()) if not expenses.empty else 0,
        "category_summary": category_summary,
        "category_totals": {
            row["Category"]: float(row["TotalSpent"])
            for _, row in category_summary.iterrows()
        },
        "refund_summary": refund_summary,
        "top_category": top_category,
        "top_category_amount": round(top_category_amount, 2),
        "top_category_percentage": round(top_category_percentage, 2),
        "largest_transaction": largest_transaction,
        "discretionary_spending": round(discretionary_spending, 2),
        "discretionary_percentage": round(discretionary_percentage, 2),
        "date_range": {
            "start": date_start.strftime("%Y-%m-%d"),
            "end": date_end.strftime("%Y-%m-%d"),
            "days": int(days_covered)
        },
        "business_insights": business_insights
    }

# Test your function
# Test your function
analysis = analyze_spending_patterns(clean_data)

print("SPENDING ANALYSIS SUMMARY")
print("-" * 50)
print(f"Total Spending: ${analysis['total_spending']:.2f}")
print(f"Total Refunds: ${analysis['total_refunds']:.2f}")
print(f"Net Spending: ${analysis['net_spending']:.2f}")
print(f"Total Transactions: {analysis['transaction_count']}")
print(f"Expense Transactions: {analysis['expense_transaction_count']}")
print(f"Refund Transactions: {analysis['refund_transaction_count']}")
print(f"Average Expense: ${analysis['average_expense']:.2f}")

print("\nCATEGORY BREAKDOWN")
print("-" * 50)
display(analysis["category_summary"])

print("\nREFUND SUMMARY")
print("-" * 50)

if not analysis["refund_summary"].empty:
    display(analysis["refund_summary"])
else:
    print("No refunds found.")

print("\nTOP SPENDING CATEGORY")
print("-" * 50)
print(f"Category: {analysis['top_category']}")
print(f"Amount: ${analysis['top_category_amount']:.2f}")
print(f"Percentage: {analysis['top_category_percentage']:.2f}%")

print("\nLARGEST TRANSACTION")
print("-" * 50)

largest = analysis["largest_transaction"]

if largest is not None:
    print(f"Date: {largest['Date']}")
    print(f"Description: {largest['Description']}")
    print(f"Category: {largest['Category']}")
    print(f"Amount: ${largest['Amount']:.2f}")
else:
    print("No expense transactions found.")

print("\nBUSINESS INSIGHTS")
print("-" * 50)

for insight in analysis["business_insights"]:
    print(f"- {insight}")

SPENDING ANALYSIS SUMMARY
--------------------------------------------------
Total Spending: $150.95
Total Refunds: $25.00
Net Spending: $125.95
Total Transactions: 5
Expense Transactions: 4
Refund Transactions: 1
Average Expense: $37.74

CATEGORY BREAKDOWN
--------------------------------------------------

,Category,TotalSpent,TransactionCount,AverageTransaction,Percentage,FormattedTotal
0,Entertainment,89.95,1,89.95,59.59,$89.95
1,Groceries,45.50,1,45.50,30.14,$45.50
2,Transport,12.00,1,12.00,7.95,$12.00
3,Coffee,3.50,1,3.50,2.32,$3.50

REFUND SUMMARY
--------------------------------------------------

  Category  TotalRefunds  RefundCount
0   Refund          25.0            1

TOP SPENDING CATEGORY
--------------------------------------------------
Category: Entertainment
Amount: $89.95
Percentage: 59.59%

LARGEST TRANSACTION
--------------------------------------------------
Date: 2024-08-03
Description: Concert Tickets
Category: Entertainment
Amount: $89.95

BUSINESS INSIGHTS
--------------------------------------------------
- Your largest spending category is Entertainment, accounting for $89.95 (59.6% of spending).
- Entertainment is a major budget driver. A 10% reduction in this category could save about $9.00 over this period.
- Flexible lifestyle categories such as coffee, dining and entertainment make up 61.9% of spending, so small habit changes could have a noticeable impact.
- Coffee spending totals $3.50. Setting a weekly coffee cap is a simple student-friendly savings action.
- Average daily spending across the period is $30.19, based on 5 day(s) of transactions.
- Refunds total $25.00. They are tracked separately so they do not hide your real spending habits.

In [60]:
# 🤖 AI Collaboration: Business Insights Generator
# Ask AI to help create professional financial recommendations

def generate_financial_recommendations(analysis_data):
    """
    Generate actionable financial recommendations based on spending analysis

    🤖 AI Collaboration Prompt:
    "Based on spending analysis data, create professional financial
    recommendations. Include specific savings opportunities, spending
    pattern observations, and actionable advice formatted for a
    personal finance app user."

    Args:
        analysis_data: Dictionary with spending analysis results
    Returns:
        str: Formatted recommendations report
    """
    import pandas as pd

    if not isinstance(analysis_data, dict):
        raise ValueError("Recommendations need the dictionary returned by analyze_spending_patterns().")

    total_spending = float(analysis_data.get("total_spending", 0) or 0)
    total_refunds = float(analysis_data.get("total_refunds", 0) or 0)
    net_spending = float(analysis_data.get("net_spending", 0) or 0)

    top_category = analysis_data.get("top_category")
    top_amount = float(analysis_data.get("top_category_amount", 0) or 0)
    top_percentage = float(analysis_data.get("top_category_percentage", 0) or 0)

    date_range = analysis_data.get("date_range", {})
    insights = analysis_data.get("business_insights", [])

    category_summary = analysis_data.get("category_summary", pd.DataFrame())

    if isinstance(category_summary, list):
        category_summary = pd.DataFrame(category_summary)
    elif isinstance(category_summary, dict):
        category_summary = pd.DataFrame(category_summary)
    elif category_summary is None:
        category_summary = pd.DataFrame()

    lines = []
    lines.append("## 💡 Budget Buddy Financial Recommendations")
    lines.append("")
    lines.append(f"**Period analysed:** {date_range.get('start', 'N/A')} to {date_range.get('end', 'N/A')}")
    lines.append(f"**Total spending:** ${total_spending:,.2f}")
    lines.append(f"**Refunds tracked separately:** ${total_refunds:,.2f}")
    lines.append(f"**Net cash impact:** ${net_spending:,.2f}")
    lines.append("")

    if total_spending <= 0:
        lines.append("### Summary")
        lines.append(
            "No positive spending transactions were found, so there is not enough spending data "
            "to make category-based recommendations."
        )
        lines.append("Add a normal month of transaction data to receive more useful budgeting guidance.")
        return "\n".join(lines)

    lines.append("### Key observations")

    if top_category:
        lines.append(
            f"- Your biggest spending area is **{top_category}** at **${top_amount:,.2f}**, "
            f"which is **{top_percentage:.1f}%** of all spending."
        )

    for insight in insights[:4]:
        lines.append(f"- {insight}")

    lines.append("")
    lines.append("### Action plan")

    if not category_summary.empty and {"Category", "TotalSpent", "Percentage"}.issubset(category_summary.columns):
        top_categories = category_summary.head(3)

        for _, row in top_categories.iterrows():
            category = str(row["Category"])
            amount = float(row["TotalSpent"])
            percentage = float(row["Percentage"])
            potential_saving = amount * 0.10

            if category.lower() == "coffee":
                action = (
                    "try a weekly coffee limit, bring coffee from home on two days, "
                    "or use campus loyalty deals"
                )
            elif category.lower() in ["dining", "restaurants", "takeaway"]:
                action = "plan two low-cost meals before buying takeaway and set a weekly eating-out cap"
            elif category.lower() == "entertainment":
                action = (
                    "choose one paid activity per week and mix in free events, "
                    "student discounts, or streaming nights"
                )
            elif category.lower() == "groceries":
                action = "shop with a list, compare unit prices, and plan meals around specials before buying"
            elif category.lower() == "transport":
                action = "compare public transport, walking, car-pooling, and ride-share costs before each trip"
            elif category.lower() == "utilities":
                action = "review usage and compare plans before the next billing cycle"
            else:
                action = "set a clear spending cap and review this category weekly"

            lines.append(
                f"- **{category}:** You spent ${amount:,.2f} ({percentage:.1f}%). "
                f"To save about ${potential_saving:,.2f}, {action}."
            )

    discretionary_percentage = float(analysis_data.get("discretionary_percentage", 0) or 0)
    discretionary_spending = float(analysis_data.get("discretionary_spending", 0) or 0)

    if discretionary_spending > 0:
        lines.append(
            f"- **Flexible spending check:** Coffee, dining and entertainment-style categories total "
            f"${discretionary_spending:,.2f} ({discretionary_percentage:.1f}%). "
            "Start with a small 5-10% reduction rather than cutting everything at once."
        )

    if total_refunds > 0:
        lines.append(
            f"- **Refund note:** You received ${total_refunds:,.2f} in refunds. "
            "Keep recording refunds separately so your budget reflects both spending behaviour and money returned."
        )

    lines.append("")
    lines.append("### Next step")
    lines.append(
        "Choose one category to improve this week, set a realistic dollar cap, "
        "and compare your next transaction export against this report."
    )
    lines.append("")
    lines.append("_This is budgeting education, not personal financial advice._")

    return "\n".join(lines)

# Test your function
recommendations = generate_financial_recommendations(analysis)
print(recommendations)

## 💡 Budget Buddy Financial Recommendations

**Period analysed:** 2024-08-01 to 2024-08-05
**Total spending:** $150.95
**Refunds tracked separately:** $25.00
**Net cash impact:** $125.95

### Key observations
- Your biggest spending area is **Entertainment** at **$89.95**, which is **59.6%** of all spending.
- Your largest spending category is Entertainment, accounting for $89.95 (59.6% of spending).
- Entertainment is a major budget driver. A 10% reduction in this category could save about $9.00 over this period.
- Flexible lifestyle categories such as coffee, dining and entertainment make up 61.9% of spending, so small habit changes could have a noticeable impact.
- Coffee spending totals $3.50. Setting a weekly coffee cap is a simple student-friendly savings action.

### Action plan
- **Entertainment:** You spent $89.95 (59.6%). To save about $9.00, choose one paid activity per week and mix in free events, student discounts, or streaming nights.
- **Groceries:** You spent $45.50 (30.1%). To save about $4.55, shop with a list, compare unit prices, and plan meals around specials before buying.
- **Transport:** You spent $12.00 (8.0%). To save about $1.20, compare public transport, walking, car-pooling, and ride-share costs before each trip.
- **Flexible spending check:** Coffee, dining and entertainment-style categories total $93.45 (61.9%). Start with a small 5-10% reduction rather than cutting everything at once.
- **Refund note:** You received $25.00 in refunds. Keep recording refunds separately so your budget reflects both spending behaviour and money returned.

### Next step
Choose one category to improve this week, set a realistic dollar cap, and compare your next transaction export against this report.

_This is budgeting education, not personal financial advice._

---

# 🌐 Advanced Features: Integrating AI Components

Once your foundation data processing is solid, integrate advanced AI features using hands-on-ai.

## Chat Interface Integration

In [ ]:
# 🤖 AI Collaboration: Financial Advice Chatbot
# Ask AI to help you create a finance-focused chat personality

from hands_on_ai import chat

def create_finance_chat_personality():
    """
    Set up a financial advisor chat personality using hands-on-ai

    🤖 AI Collaboration Prompt:
    "Help me create a system prompt for a friendly, professional financial
    advisor chatbot that can provide spending advice based on transaction
    analysis. The personality should be encouraging but practical."
    """
    # Your AI-assisted chat setup goes here
    # Include personality traits, knowledge focus, response style
    pass

# Test your chatbot
# response = chat.say("I spend too much on coffee, what should I do?")
# print(response)

## RAG System for Financial Documents

In [ ]:
# 🤖 AI Collaboration: Document Retrieval Setup
# Ask AI to help you set up RAG for financial documents

from hands_on_ai import rag

def setup_financial_rag():
    """
    Set up RAG system for financial documents and transaction data

    🤖 AI Collaboration Prompt:
    "Help me set up a RAG system that can retrieve information from
    financial documents, budgeting guides, and transaction summaries
    to answer user questions about personal finance."
    """
    # Your AI-assisted RAG setup goes here
    # Include document ingestion, query processing
    pass

# Test your RAG system
# answer = rag.ask("What's a good budgeting strategy for someone who overspends on entertainment?")
# print(answer)

## Custom Financial Tools

In [ ]:
# 🤖 AI Collaboration: Custom Tool Development
# Ask AI to help you create useful financial calculators

from hands_on_ai import agent

def create_savings_calculator_tool():
    """
    Create a custom savings goal calculator as an agent tool

    🤖 AI Collaboration Prompt:
    "Create a savings goal calculator function that takes current savings,
    monthly contribution, and target amount, then calculates time to reach
    goal. Format output for user-friendly display."
    """
    # Your AI-assisted tool implementation goes here
    # Include input validation, calculations, formatted output
    pass

# Register your tool with the agent system
# agent.register_tool("savings_calculator", create_savings_calculator_tool)

## Gradio UI Integration

In [ ]:
# 🤖 AI Collaboration: Professional UI Design
# Ask AI to help you create a comprehensive Gradio interface

import gradio as gr

def create_finance_assistant_ui():
    """
    Create a comprehensive Gradio interface for the Smart Finance Assistant

    🤖 AI Collaboration Prompt:
    "Help me design a Gradio interface that combines CSV upload, spending
    analysis, chat functionality, and custom tools in a user-friendly
    layout suitable for a personal finance application."
    """
    # Your AI-assisted UI implementation goes here
    # Include multiple tabs, file uploads, chat interface, tool access
    pass

# Launch your complete application
# demo = create_finance_assistant_ui()
# demo.launch()

---

# 🧪 STEP 6: Test with a Variety of Data

**🔍 Comprehensive Testing Strategy**

Create thorough tests for your Smart Finance Assistant to ensure it handles real-world scenarios.

::: {.callout-tip}
## 🤖 AI Collaboration for Testing

**Effective Testing Prompts:**
```
"Help me create comprehensive test cases for my finance assistant. Include:
- Normal transaction data
- Edge cases (refunds, large amounts, missing data)
- Invalid data scenarios (corrupted files, wrong formats)
- Business logic validation (spending calculations, recommendations)
Create assert statements to verify each scenario."
```
:::

## Foundation Function Tests

In [ ]:
# 🤖 AI Collaboration: Comprehensive Test Suite
# Ask AI to help you create thorough test cases

def create_test_datasets():
    """
    Create various test datasets for comprehensive testing

    🤖 AI Collaboration Prompt:
    "Create realistic test datasets for a finance assistant including:
    1. Normal spending data with various categories
    2. Edge cases: refunds (negative amounts), missing data, zero amounts
    3. Data quality issues: invalid formats, extreme values
    4. Business scenarios: high spending months, savings patterns
    Include Australian business names and realistic amounts."
    """
    # Your AI-generated test data goes here
    pass

def test_data_loading_function():
    """
    Test the data loading and cleaning functionality

    🤖 AI Collaboration Prompt:
    "Create assert statements to test my data loading function with:
    - Valid CSV data
    - CSV with dollar signs in amounts
    - Missing values and invalid data
    - Empty files and corrupted data
    Verify that cleaning works correctly and errors are handled gracefully."
    """
    print("🧪 Testing data loading function...")
    # Your AI-generated test cases go here
    pass

def test_spending_analysis():
    """
    Test spending analysis calculations

    🤖 AI Collaboration Prompt:
    "Create tests for spending analysis that verify:
    - Category totals are calculated correctly
    - Percentages add up to 100%
    - Refunds are handled appropriately
    - Edge cases like single transactions or empty categories
    Use assert statements with known expected results."
    """
    print("🧪 Testing spending analysis...")
    # Your AI-generated analysis tests go here
    pass

def test_business_insights():
    """
    Test business recommendation generation

    🤖 AI Collaboration Prompt:
    "Create tests that verify business insights are appropriate:
    - High spending categories are identified correctly
    - Savings opportunities are realistic
    - Recommendations match spending patterns
    - Output format is user-friendly"
    """
    print("🧪 Testing business insights...")
    # Your AI-generated insight tests go here
    pass

# Run all tests
print("🔍 COMPREHENSIVE TESTING SUITE")
print("=" * 40)

try:
    create_test_datasets()
    test_data_loading_function()
    test_spending_analysis()
    test_business_insights()
    print("✅ All tests passed! Your finance assistant is working correctly.")
except AssertionError as e:
    print(f"❌ Test failed: {e}")
except Exception as e:
    print(f"⚠️ Test error: {e}")

## Advanced Integration Tests

In [ ]:
# 🤖 AI Collaboration: Integration Testing
# Ask AI to help test the complete system integration

def test_full_workflow():
    """
    Test the complete workflow from CSV upload to final recommendations

    🤖 AI Collaboration Prompt:
    "Create an end-to-end test that:
    1. Loads sample CSV data
    2. Runs complete analysis pipeline
    3. Generates chat responses about the data
    4. Verifies RAG system retrieval
    5. Tests custom tool functionality
    Ensure all components work together seamlessly."
    """
    print("🧪 Testing complete workflow integration...")
    # Your AI-generated integration tests go here
    pass

def test_error_handling():
    """
    Test error handling and user experience

    🤖 AI Collaboration Prompt:
    "Create tests that verify error handling for:
    - Invalid file uploads
    - Network connection issues
    - Malformed data
    - User input validation
    Ensure error messages are user-friendly and helpful."
    """
    print("🧪 Testing error handling...")
    # Your AI-generated error tests go here
    pass

# Run integration tests
try:
    test_full_workflow()
    test_error_handling()
    print("✅ Integration tests completed successfully!")
except Exception as e:
    print(f"⚠️ Integration test issue: {e}")

---

# 📊 Project Completion Checklist

## Foundation Skills ✅
- [ ] **Data Processing**: CSV loading and cleaning functions work reliably
- [ ] **Analysis Functions**: Spending summaries calculate correctly
- [ ] **Business Insights**: Recommendations are relevant and actionable  
- [ ] **Error Handling**: Graceful handling of data issues
- [ ] **Testing**: Comprehensive test coverage for core functions
- [ ] **Documentation**: Clear AI collaboration documentation in diary

## Advanced Integration ✅
- [ ] **Chat Interface**: Finance advisor personality implemented
- [ ] **RAG System**: Document retrieval for financial guidance
- [ ] **Custom Tools**: At least one financial calculator/utility
- [ ] **Gradio UI**: Professional, user-friendly interface
- [ ] **Full Integration**: All components work together seamlessly

## Professional Standards ✅
- [ ] **Code Quality**: Professional, commented, maintainable code
- [ ] **Business Focus**: Clear connection to real finance problems
- [ ] **User Experience**: Interface suitable for non-technical users
- [ ] **AI Collaboration**: Extensive, well-documented AI usage
- [ ] **Testing**: Robust validation of all features

## Project Documentation ✅  
- [ ] **Developer's Diary**: Complete AI collaboration documentation
- [ ] **README**: Clear project description and usage instructions
- [ ] **GitHub**: Regular commits showing development progress
- [ ] **Reflection**: Thoughtful analysis of learning and challenges

---

# 🎯 Final Thoughts: Your Finance Assistant Journey

Congratulations on building your Smart Finance Assistant! This project represents a significant achievement in modern business programming:

**Technical Skills Developed:**
- AI-assisted development workflows
- Professional data processing with pandas
- Integration of multiple AI technologies
- User interface design with Gradio
- Comprehensive software testing

**Business Skills Developed:**  
- Financial data analysis and insights
- User-centered application design
- Professional documentation practices
- Iterative development methodology
- Critical evaluation of AI suggestions

**Professional Preparation:**
- Experience with industry-standard AI collaboration
- Portfolio-ready application development
- Understanding of business problem-solving with technology
- Documentation practices for workplace environments

**Your Smart Finance Assistant demonstrates your ability to direct AI tools toward meaningful business solutions - exactly the skill set that modern BIS graduates need for career success!**

---

*Remember to document all AI collaborations in your Developer's Diary and maintain regular GitHub commits throughout your development process.*